const actionTypes = {
  GET_CLINIC_LIST_SUCCESS: 'GET_CLINIC_LIST_SUCCESS',
  GET_MODELITY_LIST_SUCCESS : 'GET_MODELITY_LIST_SUCCESS',
  MODELITY_SAVE_SUCCESS : 'MODELITY_SAVE_SUCCESS',
  MODELITY_UPDATE_SUCCESS : 'MODELITY_UPDATE_SUCCESS',
  PROVIDER_LIST_SUCCESS : 'PROVIDER_LIST_SUCCESS',
  PROVIDER_UPDATED_SUCCESS : 'PROVIDER_UPDATED_SUCCESS',
  GET_ROOM_LIST_SUCCESS: 'GET_ROOM_LIST_SUCCESS',
  VIEW_SCHEDULE_LIST : 'VIEW_SCHEDULE_LIST'
}

export default actionTypes;